### ISSUE TITLE
This is clever.

### ISSUE THREAD

**Issue by aventurella** [Gentlee/SerialQueue#1]
I was looking at using `System.Collections.Concurrent.ConcurrentQueue` to do something similar, but I like the idea of `ContinueWith` and just chaining.  Have you run into any issues with this approach? Would it receive any benefit from `ConfigureAwait(continueOnCapturedContext: false);`?

**Comment by Gentlee** [comment]
@aventurella I haven't used it much bcs i'm not developing in C# for a long time. But i have tests, they show that everything should be fine. If not - feel free to make pull requests.

As for `continueOnCapturedContext: false` - i guess it would work same as without using SerialQueue, all code after await would be simply run in thread pool (and not in serial queue).
