### ISSUE TITLE
Use with selenium

### ISSUE THREAD

**Issue by Manthan2611** [Gentlee/SerialQueue#3]
Hi,

I am having some selenium code which submit a user form on a button click event.
Now selenium take some time depending on the page load and some other varies. 
In this scenario i am facing and issue as, when a user click submit button in c# form the selenium gets to work. But some time user again submit a new c# form then what happens is it drop the previous user action and start the new one. In this case the 1st form submit by user was not been completed by selenium function and selenium function start the new users submit form. 

Here what i want to archive is whenever the user submit the form it should complete it first and when the selenium function again receive new task the it should be queued somewhere in the running application so that when the task 1 get completed it should move to next task and future. 

I have tired using your code but when ever used submit the 2nd form the pending work of selenium func for 1st form get drop in the middle and its start with the 2nd form submission. 

How can i make this work using your code?

Thanks & Regards,
Manthan Patel

**Comment by Gentlee** [comment]
It is hard to answer without any code provided, there could be problems with both selenium lib or whatever you use, with destroyed first form that doesn't handle first task completion properly or smth else. I don't even know what framework you use, what platform you are developing for etc.

If you want to execute tasks serially you can write something like this:

class Form {
    static var serialQueue = new SerialQueue();

    async Task OnSubmit() {
        serialQueue.Enqueue(() => selenium.SendForm(args));
        CloseForm();
    }
}

Make sure that you don't run task before adding it to the queue but pass async function (Function<Task>).

**Comment by Manthan2611** [comment]
Hi,
I apologize for not providing the code before. 

Below is the function code which submit the form (here i have written selenium working code):

`public void submit_form(){}`

Created an async method to call the above function to call A synchronizing:

` public async Task submit_formAsync()
        {
            await Queue.Enqueue(() => submit_form());
        }` 

A Code behind of a button event:

`private async void button2_Click(object sender, EventArgs e)
        {
            await submit_formAsync();
         }` 

Now when i call button2_Click event it start the process to submit form via selenium. On running the app and click the button twice it should submit the form two time. not leave the 1st click to be destroyed and get overlapped by 2nd click. 
Is there any mechanism to achieve what i am trying to do?

**Comment by Manthan2611** [comment]
Thanks for you help! 
Will try to fix on my code,
