### ISSUE TITLE
Ability to start async Task as nested async Task

### ISSUE THREAD

**Issue by IvanMurzak** [Gentlee/SerialQueue#7]
In my project async Task can create a nested async task, which should be executed as a dependency.
In the current implementation of `SerialQueue`, it just stuck forever, because Task A waits for the completion of Task B before beginning to run Task B, and Task A waits for the completion of Task B.
```C#
var queue = new SerialQueue();
await queue.Enqueue(async () => // Task A
{
  // do something 1
  await queue.Enqueue(async () => // Task B (nested)
  {
    // do something 2
  });
});
```

**Comment by IvanMurzak** [comment]
I guess I found a solution to resolve the issue. Will try to implement the execution stack. 
```C#
public bool IsInSerialQueue
{
    get
    {
        var curTaskId = Task.CurrentId;
        if (curTaskId == null) return false;
        return _executionQueue.Any(x => x.Id == curTaskId);
    }
}
```

**Comment by IvanMurzak** [comment]
I had no luck to resolve my issue. Even after the implementation of the validation, it won't help, because there are cases when the task in the queue can generate a sub-task on itself and run it synchronously, and that sub-task may try to add a new sub-sub-task into the queue, the validation fails in this scenario. Also, the validation can't take access to parents' tasks to check them all. 

It looks like I was completely wrong about the idea in general. It is a wrong solution in my opinion. The problem should be solved out of the synchronized task execution queue.

**Comment by gen1lee** [comment]
@IvanMurzak one possible solution is to separate implementation from synchronization. So that we have logic without sync:

```c#
async Task FunctionA() {
  // job A
};
async Task FunctionB() {
  // job B
};
async Task FunctionC() {
  await FunctionA();
  // job C
  await FunctionB();
};
```

and later we put this functions to serial queue in the place where we call them.

```c#
async Task Test()
{
    queue.Enqueue(() => {
      await FunctionA();
      await FunctionB();
      await FunctionC();
    });
}
```

Or create a synchronized wrapper over original functions.

**Comment by gentlee** [comment]
Added info to readme about this case, thanks for raising the problem.

**Comment by gentlee** [comment]
@IvanMurzak one possible solution is to separate implementation from synchronization. So that we have logic without sync:

async Task FunctionA()
{
  // job A
};

async Task FunctionB()
{
  // job B
};

async Task FunctionC()
{
  await FunctionA();
  // job C
  await FunctionB();
};
and later we put this functions to serial queue in the place where we call them.

async Task Test()
{
    await queue.Enqueue(() => {
      await FunctionA();
      await FunctionB();
      await FunctionC();
    });
}
Or create a synchronized wrapper over original functions and don't nest enqueues.
